version: "3.4"
services:
  app:
    build:
      dockerfile: dev.Dockerfile
      context: .
    command: ./bin/start-watch.sh
    environment:
      SERVER_PORT: "8080"
      MONGO_HOST: mongo:27017
      ES_HOST: es:9200
      REDIS_HOST: redis:6379
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - es
      - redis
    volumes:
      - .:/workdir
  app-build:
    build:
      dockerfile: dev.Dockerfile
      context: .
    command: ./bin/build-watch.sh
    volumes:
      - .:/workdir
  app-codegen:
    build:
      dockerfile: dev.Dockerfile
      context: .
    command: ./bin/codegen-watch.sh
    volumes:
      - .:/workdir
  mongo:
    restart: always
    image: docker.pkg.github.com/anontown/mongo-image/at-mongo:db0fadb
    volumes:
      - ./data/db:/data/db
  es:
    restart: always
    image: docker.pkg.github.com/anontown/elasticsearch-image/at-elasticsearch:579c73d
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
  redis:
    restart: always
    image: docker.pkg.github.com/anontown/redis-image/at-redis:5b1114d
    volumes:
      - ./data/redis:/data
