name: ci

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $PERSONAL_TOKEN
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - name: lint
        run: docker-compose -f docker-compose.test.yml run --rm app npm run lint
      - name: run sysctl
        run: |
          sudo sysctl -w vm.max_map_count=262144
      - name: test
        run: make test
  build-and-push:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v1
      - uses: anontown/docker-image-action@master
        with:
          image-name: atcouncil
          personal-token: ${{ secrets.PERSONAL_TOKEN }}
